#!/bin/zsh

if [[ -z "$no_color" ]]; then
    color_param=--color=always
else
    color_param=--color=never
fi

target=$($base_dir/function/_ffs-parse-item $*)

if [[ -d "$target" ]]; then
    echo "$target" is a directory:
    echo
    if [[ "$ls_command" = exa ]]; then
        exa -la $color_param "$target"
    else
        ls -la $color_param "$target"
    fi
elif [[ -f "$target" ]]; then
    case "$target" in
        *.pdf)
            pdftotext "$target" - | ${=pager_command}
            ;;
        *.zip)
            unzip -l "$target" | ${=pager_command}
            ;;
        *.tar.gz)
            tar -ztvf "$target" | ${=pager_command}
            ;;
        *.tar.bz2)
            tar -jtvf "$target" | ${=pager_command}
            ;;
        *.tar.xz)
            tar -Jtvf "$target" | ${=pager_command}
            ;;
        *.tar)
            tar -tvf "$target" | ${=pager_command}
            ;;
        *.mp4|*.webm|*.avi,*.wmv,*.dat,*.3gp,*.ogv,*.mkv,*.mpg,*.mpeg,*.vob,*.fl[icv],*.m2v,*.mov,*.ts,*.mts,*.m4v,*.r[am],*.qt,*.divx,*.as[fx])
            timg -E --frames=1 --loops=1 -g $(( $COLUMNS / 2 - 4 ))x$(( $FZF_PREVIEW_LINES * 2 )) "$target"
            ;;
        *.png | *.PNG | *.Png | *.jpg | *.JPG | *.Jpg | *.jpeg | *.JPEG | *.Jpeg | *.gif | *.GIF | *.Gif | *.bmp | *.BMP | *.tiff | *.TIFF | *.tif | *.TIF)
            dim=${FZF_PREVIEW_COLUMNS}x${FZF_PREVIEW_LINES}
            if [[ $dim = x ]]; then
                dim=$(stty size < /dev/tty | awk '{print $2 "x" $1}')
            elif ! [[ $KITTY_WINDOW_ID ]] && (( FZF_PREVIEW_TOP + FZF_PREVIEW_LINES == $(stty size < /dev/tty | awk '{print $1}') )); then
                dim=${FZF_PREVIEW_COLUMNS}x$((FZF_PREVIEW_LINES - 1))
            fi

            if [[ $KITTY_WINDOW_ID ]]; then
                kitty icat --clear --transfer-mode=memory --unicode-placeholder --stdin=no --place="$dim@0x0" "$target" | sed '$d' | sed $'$s/$/\e[m/'
            elif command -v chafa > /dev/null; then
                chafa -f sixel -s "$dim" "$target"
                echo ""
            elif command -v imgcat > /dev/null; then
                imgcat -W "${dim%%x*}" -H "${dim##*x}" "$target"
            else
                file "$target"
            fi
            ;;
        *)
            ${=pager_command} "$target"
            ;;
    esac
fi
