#!/bin/zsh

function _fuzzy-fs-abspath {
    if [[ -d "$*" ]]; then
        dir=$*
        echo $(custom_cd $dir; pwd)
    else
        dir=$(custom_cd $(dirname "$*"); pwd)
        filename=$(basename "$*")
        [[ dir == "/" ]] && dir=""
        echo $dir/$filename
    fi
}
