#!/bin/zsh

function _fuzzy-fs-list-history {
    local field=list-history
    if {which gsed &> /dev/null}; then
        history | gsed -re 's/^\s*[0-9]+\s*//' | awk '!x[$0]++' | sed "s/^/$command_icon /"
    else
        history | sed -re 's/^\s*[0-9]+\s*//' | awk '!x[$0]++' | sed "s/^/$command_icon /"
    fi
}
